apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-deployment
spec:
  selector:
    matchLabels:
      app: shortener-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: shortener-service
    spec:
      containers:
      - name: token
        image: sheelprabhakar/shortener-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shortener-service
spec:
  type: NodePort
  selector:
    app: shortener-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30038
