apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-deployment
spec:
  selector:
    matchLabels:
      app: redirect-service
  replicas: 1
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      containers:
      - name: redirect
        image: sheelprabhakar/redirect-service:latest
        ports:
        - containerPort: 8080
        env:
          - name: CASSANDRA_HOST
            value: cassandra
          - name: REDIS_HOST
            value: redis-server.default.svc.cluster.local
          - name: REDIS_PASSWORD
            value: blank
---
apiVersion: v1
kind: Service
metadata:
  name: redirect-service
spec:
  type: NodePort
  selector:
    app: redirect-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30039
