name: Build redirect-service

on:
  push:
    branches: [ "dev", "main" ]
    paths: ['.github/**']
    
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    environment: stage
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
    - name: Deploy MySQ
      run: | 
        echo "Deploying MySQL Configmap"
        kubectl deploy -f mysql-configmap.yml
        echo "Deploying MySQL"
        kubectl deploy -f mysql.yml
        echo "Deploying Cassandra"
        kubectl deploy -f cassandra.yml
        echo "Deploying redis"
        kubectl deploy -f redis.yml
      working-directory: cd/backend