name: Build redirect-service

on:
  push:
    branches: [ "main","dev" ]
    paths: ['redirect-service/**', '.github/**']
  pull_request:
    branches: [ "main" ]
    paths: ['redirect-service/**']
    
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
        sparse-checkout: 'redirect-service'
        sparse-checkout-cone-mode: false
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: List File
      run: cd redirect-service
    - name: Setup Gradle exec
      run: chmod +x gradlew
    - name: Build with Gradle Wrapper
      run:  ./gradlew build

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sheelprabhakar/redirect-service:latest
