name: Build shortener-service

on:
  push:
    branches: [ "main","dev" ]
    paths: ['shortener-service/**', '.github/**']
  pull_request:
    branches: [ "main" ]
    paths: ['shortener-service/**']
    
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    environment: stage
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
        sparse-checkout: 'shortener-service'
        sparse-checkout-cone-mode: false
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Setup Gradle exec
      run: chmod +x gradlew
      working-directory: shortener-service
    - name: Change env to stage
      run: sed -i '/spring.profiles.active=dev/c\spring.profiles.active=stage' src/main/resources/application.properties
      working-directory: shortener-service

    - name: Build with Gradle Wrapper
      run:  ./gradlew build
      working-directory: shortener-service

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sheelprabhakar/shortener-service:latest
      working-directory: shortener-service

    - name: Push the Docker image
      run: docker image push sheelprabhakar/shortener-service:latest
      working-directory: shortener-service
      
    - name: Deploy shortener service
      run: kubectl apply -f shortener-service.yaml
      working-directory: shortener-service